#!/usr/bin/env bash

mkv() {
    local venv_name=""

    local usage='usage: mkv [NAME]

create a python virtual env in the current directory

examples:
    mkv
    mkv venv
    mkv my_env'

    while [[ $# -gt 0 ]]; do
        case "$1" in
        -h | --help)
            printf "%s\n" "$usage" >&2
            return 0
            ;;
        -*)
            {
                printf "unknown option: %s\n\n" "$1"
                printf "%s\n" "$usage"
            } >&2
            return 2
            ;;
        *)
            if [[ -n "$venv_name" ]]; then
                {
                    printf "too many arguments: %s\n\n" "$1"
                    printf "%s\n" "$usage"
                } >&2
                return 2
            fi
            venv_name="$1"
            ;;
        esac
        shift
    done

    if [[ -z "$venv_name" ]]; then
        venv_name="venv"
    fi

    if ! command -v python3 >/dev/null 2>&1; then
        {
            printf "%s\n\n" "python3 not found in PATH"
            printf "%s\n" "$usage"
        } >&2
        return 127
    fi

    if ! python3 -m venv -h >/dev/null 2>&1; then
        {
            printf "%s\n\n" "python3 venv module not available (try installing python3-venv)"
            printf "%s\n" "$usage"
        } >&2
        return 1
    fi

    if [[ -e "$venv_name" ]]; then
        {
            printf "directory already exists: %s\n\n" "$venv_name"
            printf "%s\n" "$usage"
        } >&2
        return 2
    fi

    if ! python3 -m venv "$venv_name"; then
        return $?
    fi

    vrun "$venv_name"
}
