#!/usr/bin/env bash

set -euo pipefail

print_usage() {
    extra_message="${1:-}"

    {
        if [[ -n "$extra_message" ]]; then
            printf "%s\n\n" "$extra_message"
        fi

        cat <<'EOF'
usage: mkv [NAME]

create a python virtual env in the current directory

examples:
    mkv
    mkv venv
    mkv my_env
EOF
    } >&2
}

check_tools() {
    if ! command -v python3 >/dev/null 2>&1; then
        print_usage "python3 not found in PATH"
        exit 127
    fi

    if ! python3 -m venv -h >/dev/null 2>&1; then
        print_usage "python3 venv module not available (try installing python3-venv)"
        exit 1
    fi
}

create_venv() {
    venv_name="$1"

    if [[ -e "$venv_name" ]]; then
        print_usage "Target already exists: $venv_name"
        exit 2
    fi

    python3 -m venv "$venv_name"
}

main() {
    venv_name=""

    while [[ $# -gt 0 ]]; do
        case "$1" in
        -h | --help)
            print_usage
            exit 0
            ;;
        -*)
            print_usage "Unknown option: $1"
            exit 2
            ;;
        *)
            if [[ -n "$venv_name" ]]; then
                print_usage "Too many arguments: $1"
                exit 2
            fi
            venv_name="$1"
            ;;
        esac
        shift
    done

    if [[ -z "$venv_name" ]]; then
        venv_name="venv"
    fi

    check_tools
    create_venv "$venv_name"
}

main "$@"
