#!/usr/bin/env bash

set -euo pipefail

print_usage() {
    extra_message="${1:-}"

    {
        if [[ -n "$extra_message" ]]; then
            printf "%s\n\n" "$extra_message"
        fi
        cat <<'EOF'
usage: touch-f FILENAME

create a new file with a starter template based on its extension

examples:
  touch-f script
  touch-f script.py
  touch-f tool.sh
  touch-f main.md
EOF
    } >&2
}

create_file() {
    file_name="$1"
    PYTHON_BODY=$(
        cat <<'EOF'
def main():
  pass


if __name__ == "__main__":
  main()
EOF
    )

    MARKDOWN_BODY=$(
        cat <<'EOF'
# title

some text

## first section
some text and a [link](https://github.com/tridimensionaal)

### second section

a list
- [ ] item
  - [ ] sub item
EOF
    )

    BASH_BODY="#!/usr/bin/env bash"

    case "$1" in
    # bash (no extension)
    *.*) ;;
    *)
        printf "%s\n" "$BASH_BODY" >"$file_name"
        chmod +x "$file_name"
        return
        ;;
    esac

    case "$1" in
    # python
    **.py)
        printf "%s" "$PYTHON_BODY" >"$file_name"
        return
        ;;
    # bash
    **.sh)
        printf "%s\n" "$BASH_BODY" >"$file_name"
        chmod +x "$file_name"
        return
        ;;
    # markdown
    **.md)
        printf "%s" "$MARKDOWN_BODY" >"$file_name"
        return
        ;;
    # else
    *)
        printf "" >"$file_name"
        return
        ;;
    esac
}

main() {

    case "${1:-}" in
    -h | --help)
        print_usage
        exit 0
        ;;
    -*)
        echo "unknown option: $1" >&2
        print_usage
        exit 2
        ;;
    esac

    # check if the filename is present
    if [[ $# -ne 1 ]]; then
        print_usage "filename is required"
        exit 2
    fi

    # check if the file exists
    file="$1"
    if [[ -e "$file" ]]; then
        print_usage "file already exists: $file"
        exit 1
    fi

    create_file "$file"
}

main "$@"
