#!/bin/bash

action(){
    case $2 in
        1)
            xdg-open "$1"
            return 1
            ;;
        2)
            less "$1"
            return 1
            ;;
        3)
            rm "$1"
            return 0
            ;;
        4)
            return 0
            ;;
        *)
            return 1
            ;;
    esac
}

process_file(){
    bol=1
    while [ $bol -eq 1 ]
    do
        file "$1"
        echo "What do yo want to do?"
        echo "- 1: Open file (xdg-open)"
        echo "- 2: View the content of the file (less)"
        echo "- 3: Remove the file"
        echo "- 4: Go to the next file"

        read -rp ">> "  option
        action "$1" "$option"
        bol=$?
    done
}


for file in *
do
    if [ -f "$file" ]
    then
        process_file "$file"
    fi 
done
