#!/bin/bash

content="
# Example of TODO.md

List of things to do in the current project.

### Todo

- [ ] First task todo 
- [ ] Second task todo 
  - [ ] Sub-task or description  

### In Progress

- [ ] Working in the current task

### Done ✓

- [x] Create my first TODO.md
"

printf "%s" "$content" > TODO.md
