#!/usr/bin/env bash

set -euo pipefail

print_usage() {
    extra_message="${1:-}"

    {

        if [[ -n "$extra_message" ]]; then
            printf "%s\n\n" "$extra_message"
        fi

        cat <<'EOF'
usage: mv-lst-file --input-dir DIR --output-dir DIR

move the most recently modified file from input dir to output dir

examples:
    mv-lst-file --input-dir "$HOME/Downloads" --output-dir "."
    mv-lst-file --input-dir "$HOME/Pictures/Screenshots" --output-dir ./image.png
EOF
    } >&2

}

mv_lst_file() {
    src_dir="$1"
    dst_dir="$2"

    # move the most recently modified file from src_dir into dst_dir.
    # 1) list files with their mtime as "timestamp<TAB>path<NUL>" (NUL-delimited)
    # 2) sort newest first and take the first entry (NUL-aware)
    # 3) use read -d '' to avoid NUL loss in command substitution
    # 4) read the NUL-terminated record, split on TAB (\t),
    #    ignore timestamp (_), keep path (last_file_name)
    IFS=$'\t' read -r -d '' _ last_file_name < <(
        find "$src_dir" -maxdepth 1 -type f \
            -printf '%T@\t%p\0' |
            sort -z -nr | head -z -n 1
    ) || true

    # check if last_file_name exists
    if [[ -z "$last_file_name" ]]; then
        print_usage "No files found in $src_dir"
        exit 1
    fi

    mv -- "$last_file_name" "$dst_dir"

}

main() {

    src_dir=""
    dst_dir=""

    # check flags
    while [[ $# -gt 0 ]]; do
        case "$1" in
        -i | --input-dir)
            shift
            src_dir="$1"
            ;;
        -o | --output-dir)
            shift
            dst_dir="$1"
            ;;
        -h | --help)
            print_usage
            exit 0
            ;;
        *)
            print_usage "Unknown option: $1"
            exit 2
            ;;
        esac
        shift
    done

    # check if src_dir and dst_dir exist
    if [[ -z "$src_dir" || -z "$dst_dir" ]]; then
        print_usage "Both --input-dir and --output-dir are required"
        exit 2
    fi

    # check if src_dir is a dir
    if [[ ! -d "$src_dir" ]]; then
        print_usage "Input dir not found: $src_dir"
        exit 2
    fi

    # check if dst_dir is a dir
    if [[ ! -d "$dst_dir" ]]; then
        print_usage "Output dir not found: $dst_dir"
        exit 2
    fi

    # mv file
    mv_lst_file "$src_dir" "$dst_dir"
}

main "$@"
