#!/bin/bash         
process_file(){ 
    while IFS= read -r line
    do
        if [ "$line" == "# start shellcheck-all" ]
        then    
            break 
        fi 
        printf "%s\n" "$line" >> "$1".new.file
    done < "$1" 

    shellcheck "$1"> "$1".shell.check
}


printf "Correct the following files:\n"

for file in *
do 
    process_file "$file"
    if [ -s "$file".shell.check ]
    then
        printf "# start shellcheck-all\n" >> "$file".new.file

        while IFS= read -r line
        do
            printf "# %s\n" "$line" >> "$file".new.file
        done < "$file".shell.check
        
        printf " - %s\n" "$file"
    fi
    cat "$file".new.file > "$file"
    rm "$file".new.file
    rm "$file".shell.check
done
