#! /bin/bash

text=""
case "$1" in
    # python 
    **.py)
    text=$(which python3)
        printf "#!%s\n" "$text" | cat > "$1"; chmod 744 "$1"
        ;;

    # javascript 
    **.js)
        text=$(which node)
        printf "#!%s\n" "$text" | cat > "$1"; chmod 774 "$1"
        ;;

    # bash  
    **.sh)
        text=$(which bash)
        printf "#!%s" "$text" | cat > "$1"; chmod 744 "$1"
        ;;

    # c
    **.c)
        text="#include<stdio.h>
        
        int main(){
        }
        "
        printf "%s" "$text" | cat > "$1";
        ;;

    **.cpp)
        text="#include<iostream>
        
        using namespace std;
        
        int main(){
        }
        "
        printf "%s" "$text" | cat > "$1";
        ;;

    # else 
    *)
        touch "$1"
    ;;
esac

# start shellcheck-all
# 
# In touch-f line 7:
#     text=$(which python3)
#            ^---^ SC2230: which is non-standard. Use builtin 'command -v' instead.
# 
# 
# In touch-f line 13:
#         text=$(which node)
#                ^---^ SC2230: which is non-standard. Use builtin 'command -v' instead.
# 
# 
# In touch-f line 19:
#         text=$(which bash)
#                ^---^ SC2230: which is non-standard. Use builtin 'command -v' instead.
# 
# For more information:
#   https://www.shellcheck.net/wiki/SC2230 -- which is non-standard. Use builti...
