#! /bin/bash

text=""
case "$1" in
    # python 
    **.py)
        text1=$(command -v python3)
        text2="def main():"
        text3="    pass"
        text4="if __name__ == \"__main__\":"
        text5="    main()"
        printf "#!%s\n\n%s\n%s\n\n\n%s\n%s\n" "$text1" "$text2" "$text3" "$text4" "$text5" | 
            cat > "$1"; chmod 744 "$1"
        ;;

    # javascript 
    **.js)
        text=$(command -v node)
        printf "#!%s\n" "$text" | cat > "$1"; chmod 774 "$1"
        ;;

    # bash  
    **.sh)
        text=$(command -v bash)
        printf "#!%s" "$text" | cat > "$1"; chmod 744 "$1"
        ;;

    # c
    **.c)
        text1="#include<stdio.h>"
        text2="int main(){"
        text3="}"
        printf "%s\n\n%s\n%s" "$text1" "$text2" "$text3" | cat > "$1";
        ;;

    **.cpp)
        text1="#include<iostream>"
        text2="using namespace std;"
        text3="int main(){"
        text4="}"
        printf "%s\n%s\n\n%s\n%s" "$text1" "$text2" "$text3" "$text4" | cat > "$1";
        ;;

    # else 
    *)
        touch "$1"
    ;;
esac

